apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-16T18:04:11Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1822"
  uid: 3ef8ecfa-76c3-4206-b218-1bf4ba7e1759
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.189.27
  clusterIPs:
  - 10.98.189.27
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31357
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
